services:
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
    container_name: es01
    restart: always
    ports:
      - ${ES_PORT}:9200
    volumes:
      - esdata01:/usr/share/elasticsearch/data
  kibana:
    image: docker.elastic.co/kibana/kibana:${STACK_VERSION}
    container_name: kib01
    restart: always
    ports:
      - ${KIBANA_PORT}:5601
    volumes:
      - kibanadata:/usr/share/kibana/data
    environment:
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=${KIBANA_PASSWORD}

volumes:
  esdata01:
    driver: local
  kibanadata:
    driver: local

networks:
  default:
    name: elastic-docker
    driver: bridge